"""users, book owner, frame seed bigint

Revision ID: 6ad4004f94f2
Revises: 6cbe4ec3ef53
Create Date: 2026-09-10 23:54:28.644277

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6ad4004f94f2'
down_revision: str | None = '6cbe4ec3ef53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('books', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_books_owner_id'), 'books', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('frames', 'seed',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frames', 'seed',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_owner_id'), table_name='books')
    op.drop_column('books', 'owner_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
