"""book source and pdf page map

Revision ID: be7ecd4ea112
Revises: 6ad4004f94f2
Create Date: 2026-09-11 11:15:34.134602

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'be7ecd4ea112'
down_revision: str | None = '6ad4004f94f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('source_key', sa.String(length=1000), nullable=True))
    op.add_column('books', sa.Column('source_content_type', sa.String(length=200), nullable=True))
    op.add_column('pages', sa.Column('pdf_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'pdf_page')
    op.drop_column('books', 'source_content_type')
    op.drop_column('books', 'source_key')
    # ### end Alembic commands ###
