import requests
from app.agents.types.types import AgentState
from app.prompts import build_artist_prompt
from langchain_google_genai import ChatGoogleGenerativeAI
from google import genai
from app.schemas import ArtistOutputSchema
from app.services.image_service import upload_image_to_s3
from dotenv import load_dotenv;
from PIL import Image
import os
import io
load_dotenv();
gemini_api_key = os.getenv("GOOGLE_API_KEY");

client = genai.Client(api_key=gemini_api_key);

async def artist_agent(state: AgentState) -> AgentState:
    """This agent will generate an image based on the director agent's output
        Args:
            state (AgentState): Current state of the agent
        Returns:
            AgentState: Updated state with artist output
    """
    director_output = state["director_output"]
    prev_image_url = state["prev_image_url"]
    visual_style = state["memory"]["visual_style"]
    prompt = build_artist_prompt(director_output, visual_style, prev_image_url)
    
    contents = [prompt]
    
    if prev_image_url:
        resp = requests.get(prev_image_url)
        resp.raise_for_status()
        prev_image = Image.open(io.BytesIO(resp.content));
        contents.append(prev_image)
        
    
    response = client.models.generate_content(
        model="gemini-2.5-flash-image",
        contents=[prompt, prev_image] if prev_image_url else [prompt],
        
        
    )
    
    for part in response.parts:
        if part.text is not None:
            print(part.text)
        elif part.inline_data is not None:
            image = part.as_image()
            image_bytes = image.image_bytes
            image_name = 
            current_image_url = await upload_image_to_s3(bucket_name="comicly", image_bytes=image_bytes, object_name="");
            state["current_image_url"] = current_image_url
            return state
    raise RuntimeError("No image generated by artist agent")
            
    
    

    
    
    
    
    
    
    
            
                